spring:
  redis:
    host: redis-11073.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 11073
    username: default
    password: ${REDIS_PASSWORD}
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.wodjz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

logging:
  level:
    root: INFO
