spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journalDB
      database: journalDB
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    root: INFO

weather:
  api:
    key: b53c7c7988f652a9c4e592b3acc9c1ed

tts:
  api:
    key: sk_5ff93000d31e3f3c4c9252dfd0e4ead3a94ad340b4d251a8
