spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journalDB
      database: journalDB
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    root: INFO

weather:
  api:
    key: b53c7c7988f652a9c4e592b3acc9c1ed
